#!/usr/bin/env bats
# End-to-end smoke tests for runtime/codex-review.sh (task-006, Phase D)
#
# Scenarios:
#   1. no args                         -> usage, exit 1
#   2. base-done 미충족                -> 전제 실패, codex 미호출
#   3. approved 리뷰                   -> reviews/001.md + pinned flags + approved-done passes
#   4. 두 번째 리뷰                    -> 002.md 누적 (001 유지)
#   5. 세션 가드 (no FORCE)            -> non-zero, no review
#   6. staging 검증 실패(invalid)      -> 승격 안 함, exit 1
#   7. codex 부재                      -> exit 1

setup() {
    REPO="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
    WORK="$(mktemp -d)"
    mkdir -p "$WORK/runtime/config" "$WORK/kb/tasks" "$WORK/kb/artifacts"
    cp -r "$REPO/runtime/validator" "$WORK/runtime/"
    cp -r "$REPO/runtime/lib"       "$WORK/runtime/"
    cp "$REPO/runtime/codex-review.sh" "$WORK/runtime/"
    cp "$REPO/runtime/render-prompt.py" "$WORK/runtime/"
    cp "$REPO/runtime/config/model-profiles.json" "$WORK/runtime/config/"
    cp "$REPO/collab.md" "$WORK/collab.md"
    cp -R "$REPO/templates" "$WORK/templates"
    chmod +x "$WORK/runtime/"*.sh
    git init -q "$WORK" 2>/dev/null || true
    export WORK REPO
    unset CLAUDE_CODE_SESSION CLAUDE_CODE_SESSION_ID CLAUDECODE CLAUDE_CODE CODEX_AUTO_FORCE
}
teardown() { rm -rf "$WORK"; }

_setup_done() { # <id>
    local id="$1" d="$WORK/kb/tasks/$1"
    mkdir -p "$d"
    cp "$REPO/tests/validator/fixtures/good.md" "$d/design.md"
    printf '# n\n\n> Status: done\n> Inputs: x\n> Outputs: y\n> Next step: z\n\n## 산출물\n- a\n' > "$d/implementation-notes.md"
    printf '# s\n\n> Status: done\n> Inputs: x\n> Outputs: y\n> Next step: z\n' > "$WORK/kb/artifacts/$id-summary.md"
    printf -- '- **task_id**: %s\n- **inputs**: x\n- **concepts_needed**: 없음\n- **related_files**: y\n' "$id" > "$d/manifest.md"
}

_codex_stub() { # <id> <status>
    cat > "$WORK/codex" <<EOF
#!/usr/bin/env bash
if [ "\${1:-}" = "--version" ]; then echo "codex-cli 99.0.0"; exit 0; fi
printf '%s\n' "\$*" >> "$WORK/cr-args.log"
cat > "$WORK/kb/tasks/$1/.review-staging.md" <<'R'
## Review: $1 — 2026-07-05

- **Reviewer**: Codex
- **Target**: kb/tasks/$1/implementation-notes.md
- **Review status**: $2
- **Generated by**: review=codex gpt-5.5/xhigh @codex 99.0.0, 2026-07-05 (sandbox=workspace-write)
- **Feedback**:
  - 검토 내용.
- **Action required**:
  - 없음
R
exit 0
EOF
    chmod +x "$WORK/codex"
}

@test "no args -> usage and exit 1" {
    run bash "$WORK/runtime/codex-review.sh"
    [ "$status" -eq 1 ]
    [[ "$output" == *"사용법"* ]]
}

@test "base-done unmet -> preflight fails, codex not called" {
    mkdir -p "$WORK/kb/tasks/task-b"
    cp "$REPO/tests/validator/fixtures/good.md" "$WORK/kb/tasks/task-b/design.md"
    _codex_stub task-b approved
    PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-b
    [ "$status" -ne 0 ]
    [ ! -f "$WORK/cr-args.log" ]
}

@test "approved review -> reviews/001.md + pinned flags + approved-done passes" {
    _setup_done task-a
    _codex_stub task-a approved
    PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    [ "$status" -eq 0 ]
    [ -f "$WORK/kb/tasks/task-a/reviews/001.md" ]
    args=$(cat "$WORK/cr-args.log")
    [[ "$args" == *"-m gpt-5.5"* ]]
    [[ "$args" == *"model_reasoning_effort=xhigh"* ]]
    [[ "$args" == *"--sandbox workspace-write"* ]]
    [[ "$args" != *"--skip-git-repo-check"* ]]
    CWC_REPO_ROOT="$WORK" run python3 "$WORK/runtime/validator/cli.py" --check-done task-a
    [ "$status" -eq 0 ]
}

@test "second review accrues 002.md (001 kept)" {
    _setup_done task-a
    _codex_stub task-a approved
    PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    _codex_stub task-a request-changes
    PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    [ "$status" -eq 0 ]
    [ -f "$WORK/kb/tasks/task-a/reviews/001.md" ]
    [ -f "$WORK/kb/tasks/task-a/reviews/002.md" ]
    # 최신 request-changes -> done 실패 + no-auto-revert
    CWC_REPO_ROOT="$WORK" run python3 "$WORK/runtime/validator/cli.py" --check-done task-a
    [ "$status" -ne 0 ]
    grep -q "Status: done" "$WORK/kb/tasks/task-a/implementation-notes.md"
}

@test "session guard -> non-zero, no review" {
    _setup_done task-a
    _codex_stub task-a approved
    CLAUDE_CODE_SESSION=1 PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    [ "$status" -ne 0 ]
    [ ! -d "$WORK/kb/tasks/task-a/reviews" ]
}

@test "invalid staging review -> not promoted, exit 1" {
    _setup_done task-a
    # 스텁이 잘못된 status 로 staging 작성
    _codex_stub task-a not-an-enum
    PATH="$WORK:/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    [ "$status" -ne 0 ]
    [ ! -f "$WORK/kb/tasks/task-a/reviews/001.md" ]
}

@test "codex missing -> exit 1" {
    _setup_done task-a
    PATH="/usr/bin:/bin" run bash "$WORK/runtime/codex-review.sh" task-a
    [ "$status" -ne 0 ]
}
