#Requires -Version 5.1
<#
.SYNOPSIS
    Pester 5 tests for runtime/codex-review.ps1 — bats(codex-review.bats) 미러 (task-006).

.DESCRIPTION
    시나리오:
      1. 인자 없음                     -> NON-ZERO
      2. base-done 미충족              -> 전제 실패, codex 미호출
      3. approved 리뷰                 -> reviews/001.md + pinned flags + approved-done passes
      4. 두 번째 리뷰                  -> 002.md 누적 + no-auto-revert
      5. 세션 가드                     -> NON-ZERO, no review
      6. invalid staging review         -> 승격 안 함
      7. codex 부재                    -> NON-ZERO
#>

BeforeAll {
    $script:Repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
    $script:Shell = $null
    $shellCmd = Get-Command pwsh -ErrorAction SilentlyContinue
    if (-not $shellCmd) { $shellCmd = Get-Command powershell -ErrorAction SilentlyContinue }
    if ($shellCmd) { $script:Shell = $shellCmd.Source }
    $script:IsWin = ($IsWindows -or ($env:OS -match "Windows"))
    $script:Py = $null
    foreach ($c in @("python3", "python")) {
        $f = Get-Command $c -CommandType Application -ErrorAction SilentlyContinue
        if ($f) { $script:Py = $f.Source; break }
    }

    function New-Workspace {
        $work = Join-Path ([System.IO.Path]::GetTempPath()) ("cwc-cr-" + [System.Guid]::NewGuid().ToString("N"))
        New-Item -ItemType Directory -Path (Join-Path $work "runtime\config") -Force | Out-Null
        New-Item -ItemType Directory -Path (Join-Path $work "kb\tasks") -Force | Out-Null
        New-Item -ItemType Directory -Path (Join-Path $work "kb\artifacts") -Force | Out-Null
        Copy-Item (Join-Path $script:Repo "runtime\validator") (Join-Path $work "runtime\") -Recurse
        Copy-Item (Join-Path $script:Repo "runtime\lib")       (Join-Path $work "runtime\") -Recurse
        Copy-Item (Join-Path $script:Repo "runtime\codex-review.ps1") (Join-Path $work "runtime\")
        Copy-Item (Join-Path $script:Repo "runtime\render-prompt.py") (Join-Path $work "runtime\")
        Copy-Item (Join-Path $script:Repo "runtime\config\model-profiles.json") (Join-Path $work "runtime\config\")
        Copy-Item (Join-Path $script:Repo "collab.md") (Join-Path $work "collab.md")
        Copy-Item (Join-Path $script:Repo "templates") (Join-Path $work "templates") -Recurse
        & git init -q $work 2>$null | Out-Null
        return $work
    }

    function Setup-DoneTask {
        param([string]$Work, [string]$Id)
        $d = Join-Path $Work "kb\tasks\$Id"
        New-Item -ItemType Directory -Path $d -Force | Out-Null
        Copy-Item (Join-Path $script:Repo "tests\validator\fixtures\good.md") (Join-Path $d "design.md")
        $u8 = [System.Text.UTF8Encoding]::new($false)
        [System.IO.File]::WriteAllText((Join-Path $d "implementation-notes.md"),
            "# n`n`n> Status: done`n> Inputs: x`n> Outputs: y`n> Next step: z`n`n## 산출물`n- a`n", $u8)
        [System.IO.File]::WriteAllText((Join-Path $Work "kb\artifacts\$Id-summary.md"),
            "# s`n`n> Status: done`n> Inputs: x`n> Outputs: y`n> Next step: z`n", $u8)
        [System.IO.File]::WriteAllText((Join-Path $d "manifest.md"),
            "- **task_id**: $Id`n- **inputs**: x`n- **concepts_needed**: 없음`n- **related_files**: y`n", $u8)
    }

    # codex 스텁: --version 응답 + exec 시 미리 써둔 review-content.md 를 staging 으로 복사.
    function Install-CodexStub {
        param([string]$Work, [string]$Id, [string]$Status, [string]$ArgsLog = "", [string]$Version = "99.0.0")
        $u8 = [System.Text.UTF8Encoding]::new($false)
        $content = @"
## Review: $Id — 2026-07-05

- **Reviewer**: Codex
- **Target**: kb/tasks/$Id/implementation-notes.md
- **Review status**: $Status
- **Generated by**: review=codex gpt-5.5/xhigh @codex $Version, 2026-07-05 (sandbox=workspace-write)
- **Feedback**:
  - review body.
- **Action required**:
  - none
"@
        $contentPath = Join-Path $Work "review-content.md"
        [System.IO.File]::WriteAllText($contentPath, $content, $u8)
        $staging = Join-Path $Work "kb\tasks\$Id\.review-staging.md"
        $binDir = Join-Path $Work "bin"
        New-Item -ItemType Directory -Path $binDir -Force | Out-Null
        if ($script:IsWin) {
            $lines = @("@echo off", "if `"%~1`"==`"--version`" ( echo codex-cli $Version & exit /b 0 )")
            if ($ArgsLog) { $lines += "echo %* >> `"$ArgsLog`"" }
            $lines += "copy /y `"$contentPath`" `"$staging`" >nul"
            $lines += "exit /b 0"
            Set-Content -Path (Join-Path $binDir "codex.cmd") -Value ($lines -join "`r`n") -Encoding ASCII
        } else {
            $lines = @('#!/usr/bin/env bash', ('if [ "${1:-}" = "--version" ]; then echo "codex-cli ' + $Version + '"; exit 0; fi'))
            if ($ArgsLog) { $lines += ('printf ''%s\n'' "$*" >> "' + $ArgsLog + '"') }
            $lines += ("cp '" + $contentPath + "' '" + $staging + "'")
            $lines += 'exit 0'
            Set-Content -Path (Join-Path $binDir "codex") -Value ($lines -join "`n") -Encoding ASCII
            & chmod +x (Join-Path $binDir "codex") 2>$null | Out-Null
        }
        return $binDir
    }

    function Get-SystemPath {
        if ($script:IsWin) { return "$env:SystemRoot\System32;$env:SystemRoot" }
        return "/usr/bin:/bin"
    }

    function Invoke-Script {
        param([string]$ScriptPath, [string[]]$ScriptArgs = @(), [hashtable]$ExtraEnv = @{})
        $clear = @("CLAUDE_CODE_SESSION", "CLAUDE_CODE_SESSION_ID", "CLAUDECODE", "CLAUDE_CODE", "CODEX_AUTO_FORCE")
        $saved = @{}
        foreach ($k in $clear) { $saved[$k] = [Environment]::GetEnvironmentVariable($k); [Environment]::SetEnvironmentVariable($k, $null) }
        $savedExtra = @{}
        foreach ($k in $ExtraEnv.Keys) { $savedExtra[$k] = [Environment]::GetEnvironmentVariable($k); [Environment]::SetEnvironmentVariable($k, $ExtraEnv[$k]) }
        try {
            $argList = @("-NoProfile", "-NonInteractive", "-File", $ScriptPath) + $ScriptArgs
            $out = & $script:Shell @argList 2>&1 | Out-String
            return [pscustomobject]@{ ExitCode = $LASTEXITCODE; Output = $out }
        }
        finally {
            foreach ($k in $ExtraEnv.Keys) { [Environment]::SetEnvironmentVariable($k, $savedExtra[$k]) }
            foreach ($k in $clear) { [Environment]::SetEnvironmentVariable($k, $saved[$k]) }
        }
    }

    function Check-Done {
        param([string]$Work, [string]$Id)
        & $script:Py (Join-Path $Work "runtime\validator\cli.py") "--check-done" $Id 2>&1 | Out-Null
        return $LASTEXITCODE
    }
}

Describe "codex-review.ps1" -Skip:([string]::IsNullOrEmpty($script:Shell)) {

    BeforeEach {
        $script:Work = New-Workspace
        $script:ScriptPath = Join-Path $script:Work "runtime\codex-review.ps1"
        $script:SysPath = Get-SystemPath
    }

    AfterEach {
        if ($script:Work -and (Test-Path $script:Work)) {
            Remove-Item $script:Work -Recurse -Force -ErrorAction SilentlyContinue
        }
    }

    It "no args (Mandatory TaskId missing) -> NON-ZERO" {
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @()
        $r.ExitCode | Should -Not -Be 0
    }

    It "base-done 미충족 -> 전제 실패, codex 미호출" {
        $d = Join-Path $script:Work "kb\tasks\task-b"
        New-Item -ItemType Directory -Path $d -Force | Out-Null
        Copy-Item (Join-Path $script:Repo "tests\validator\fixtures\good.md") (Join-Path $d "design.md")
        $argsLog = Join-Path $script:Work "cr-args.log"
        $binDir = Install-CodexStub -Work $script:Work -Id "task-b" -Status "approved" -ArgsLog $argsLog
        $p = "$binDir$([IO.Path]::PathSeparator)$($script:SysPath)"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-b") -ExtraEnv @{ PATH = $p }
        $r.ExitCode | Should -Not -Be 0
        (Test-Path $argsLog) | Should -BeFalse
    }

    It "approved review -> reviews/001.md + pinned flags + approved-done passes" {
        Setup-DoneTask -Work $script:Work -Id "task-a"
        $argsLog = Join-Path $script:Work "cr-args.log"
        $binDir = Install-CodexStub -Work $script:Work -Id "task-a" -Status "approved" -ArgsLog $argsLog
        $p = "$binDir$([IO.Path]::PathSeparator)$($script:SysPath)"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $p }
        $r.ExitCode | Should -Be 0
        (Test-Path (Join-Path $script:Work "kb\tasks\task-a\reviews\001.md")) | Should -BeTrue
        $stubArgs = Get-Content $argsLog -Raw
        $stubArgs | Should -Match "-m gpt-5\.5"
        $stubArgs | Should -Match "model_reasoning_effort=xhigh"
        $stubArgs | Should -Match "--sandbox workspace-write"
        $stubArgs | Should -Not -Match "--skip-git-repo-check"
        if ($script:Py) { (Check-Done -Work $script:Work -Id "task-a") | Should -Be 0 }
    }

    It "second review accrues 002.md + no-auto-revert" {
        Setup-DoneTask -Work $script:Work -Id "task-a"
        $binDir = Install-CodexStub -Work $script:Work -Id "task-a" -Status "approved"
        $p = "$binDir$([IO.Path]::PathSeparator)$($script:SysPath)"
        Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $p } | Out-Null
        $binDir2 = Install-CodexStub -Work $script:Work -Id "task-a" -Status "request-changes"
        $p2 = "$binDir2$([IO.Path]::PathSeparator)$($script:SysPath)"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $p2 }
        $r.ExitCode | Should -Be 0
        (Test-Path (Join-Path $script:Work "kb\tasks\task-a\reviews\001.md")) | Should -BeTrue
        (Test-Path (Join-Path $script:Work "kb\tasks\task-a\reviews\002.md")) | Should -BeTrue
        if ($script:Py) { (Check-Done -Work $script:Work -Id "task-a") | Should -Not -Be 0 }
        (Get-Content (Join-Path $script:Work "kb\tasks\task-a\implementation-notes.md") -Raw) | Should -Match "Status: done"
    }

    It "session guard -> non-zero, no review" {
        Setup-DoneTask -Work $script:Work -Id "task-a"
        $binDir = Install-CodexStub -Work $script:Work -Id "task-a" -Status "approved"
        $p = "$binDir$([IO.Path]::PathSeparator)$($script:SysPath)"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $p; CLAUDE_CODE_SESSION = "1" }
        $r.ExitCode | Should -Not -Be 0
        (Test-Path (Join-Path $script:Work "kb\tasks\task-a\reviews")) | Should -BeFalse
    }

    It "invalid staging review -> not promoted, exit 1" {
        Setup-DoneTask -Work $script:Work -Id "task-a"
        $binDir = Install-CodexStub -Work $script:Work -Id "task-a" -Status "not-an-enum"
        $p = "$binDir$([IO.Path]::PathSeparator)$($script:SysPath)"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $p }
        $r.ExitCode | Should -Not -Be 0
        (Test-Path (Join-Path $script:Work "kb\tasks\task-a\reviews\001.md")) | Should -BeFalse
    }

    It "codex missing -> non-zero" {
        Setup-DoneTask -Work $script:Work -Id "task-a"
        $r = Invoke-Script -ScriptPath $script:ScriptPath -ScriptArgs @("task-a") -ExtraEnv @{ PATH = $script:SysPath }
        $r.ExitCode | Should -Not -Be 0
    }
}
