"""Unit tests for validator.review_rules (task-006, Phase D)."""

from __future__ import annotations

from pathlib import Path

import pytest

from validator.rules import load_schema
from validator.review_rules import (
    ReviewConfigError,
    check_review,
    latest_review,
    load_review_enum,
    parse_review_fields,
    review_status,
)


@pytest.fixture(scope="module")
def schema():
    return load_schema()


VALID_REVIEW = """## Review: task-x — 2026-07-05

- **Reviewer**: Codex
- **Target**: kb/tasks/task-x/implementation-notes.md
- **Review status**: approved
- **Generated by**: review=codex gpt-5.5/xhigh @codex 0.142.4, 2026-07-05 (sandbox=workspace-write)
- **Feedback**:
  - 구현이 설계를 충실히 따른다.
- **Action required**:
  - 없음
"""


def _collab(tmp_path: Path, enum_line="<!-- review-status-enum: pending | request-changes | approved | rejected -->"):
    (tmp_path / "collab.md").write_text(f"# collab\n\n{enum_line}\n", encoding="utf-8")
    return tmp_path


def test_load_enum_from_marker(tmp_path, schema):
    root = _collab(tmp_path)
    assert load_review_enum(root, schema) == ["pending", "request-changes", "approved", "rejected"]


def test_load_enum_missing_marker_raises(tmp_path, schema):
    (tmp_path / "collab.md").write_text("# collab\n(no marker)\n", encoding="utf-8")
    with pytest.raises(ReviewConfigError):
        load_review_enum(tmp_path, schema)


def test_load_enum_missing_file_raises(tmp_path, schema):
    with pytest.raises(ReviewConfigError):
        load_review_enum(tmp_path, schema)


def test_parse_fields_inline_and_body(schema):
    fields = parse_review_fields(VALID_REVIEW)
    assert fields["Reviewer"]["inline"] == "Codex"
    assert fields["Review status"]["inline"] == "approved"
    assert any("충실히" in b for b in fields["Feedback"]["body"])
    assert "없음" in fields["Action required"]["body"]


def test_check_review_valid(schema):
    enum = ["pending", "request-changes", "approved", "rejected"]
    assert check_review(VALID_REVIEW, schema, enum) == []


def test_check_review_missing_field(schema):
    enum = ["pending", "request-changes", "approved", "rejected"]
    text = VALID_REVIEW.replace("- **Reviewer**: Codex\n", "")
    codes = [e.code for e in check_review(text, schema, enum)]
    assert "review_field_missing" in codes


def test_check_review_empty_feedback(schema):
    enum = ["pending", "request-changes", "approved", "rejected"]
    text = VALID_REVIEW.replace("  - 구현이 설계를 충실히 따른다.\n", "")
    codes = [e.code for e in check_review(text, schema, enum)]
    assert "review_field_empty" in codes


def test_check_review_placeholder_feedback_rejected(schema):
    """템플릿 placeholder 그대로면 빈값으로 취급."""
    enum = ["pending", "request-changes", "approved", "rejected"]
    text = VALID_REVIEW.replace("  - 구현이 설계를 충실히 따른다.\n", "  - (구현 결과에 대한 리뷰 내용)\n")
    codes = [e.code for e in check_review(text, schema, enum)]
    assert "review_field_empty" in codes


def test_check_review_invalid_status(schema):
    enum = ["pending", "request-changes", "approved", "rejected"]
    text = VALID_REVIEW.replace("Review status**: approved", "Review status**: maybe")
    codes = [e.code for e in check_review(text, schema, enum)]
    assert "review_status_invalid" in codes


def test_check_review_all_enum_values_accepted(schema):
    enum = ["pending", "request-changes", "approved", "rejected"]
    for status in enum:
        text = VALID_REVIEW.replace("Review status**: approved", f"Review status**: {status}")
        assert check_review(text, schema, enum) == [], status


def test_review_status_extraction(schema):
    assert review_status(VALID_REVIEW, schema) == "approved"


def test_latest_review_numeric_sort(tmp_path, schema):
    d = tmp_path / "reviews"
    d.mkdir()
    for name in ("001.md", "002.md", "010.md"):
        (d / name).write_text(VALID_REVIEW, encoding="utf-8")
    assert latest_review(d, schema).name == "010.md"


def test_latest_review_empty_dir(tmp_path, schema):
    d = tmp_path / "reviews"
    d.mkdir()
    assert latest_review(d, schema) is None


def test_latest_review_ignores_nonconforming(tmp_path, schema):
    d = tmp_path / "reviews"
    d.mkdir()
    (d / "001.md").write_text(VALID_REVIEW, encoding="utf-8")
    (d / "draft.md").write_text(VALID_REVIEW, encoding="utf-8")
    (d / "1.md").write_text(VALID_REVIEW, encoding="utf-8")
    assert latest_review(d, schema).name == "001.md"
